#!/bin/bash

docker run -d --name=spawning-pool --restart on-failure  -e MYSQL_ROOT_PASSWORD=Kerrigan \
-v hatchery:/var/lib/mysql -e MYSQL_DATABASE=zerglings mysql --default-authentication-plugin=mysql_native_password
