#!/bin/bash

docker network create zerg
docker network connect zerg spawning-pool
docker run --network zerg \
-d --name lair -p 8080:80 \
-e WORDPRESS_DB_NAME=zerglings \
-e WORDPRESS_DB_HOST=spawning-pool \
-e WORDPRESS_DB_USER=root \
-e WORDPRESS_DB_PASSWORD=Kerrigan wordpress
